project_info:
  ref_no: RFA-001/CW/STR/2025
  project_name: Water Suppy and Distribution, Dhaka
  project_client: VolumeZero Ltd.
  rev_no: 02
  date: 20/11/2025

alum_profiles:
  - profile_name: M 125x60x2.5
    web_length: 125
    flange_length: 60
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    plastic_x: 35.9
    plastic_y: 58.4
    Z_x: 60554.7
    F_y: 172.4
    Mn_yield: 10.44
    Mn_lb: 9.68
    phi_Mn: 8.71
  
  - profile_name: M 145x67x2.5
    web_length: 145
    flange_length: 67
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    plastic_x: 35.9
    plastic_y: 58.4
    Z_x: 60554.7
    F_y: 172.4
    Mn_yield: 10.44
    Mn_lb: 9.68
    phi_Mn: 8.71

steel_profiles:
  - profile_name: RHS 110x45x2.5
    web_length: 125
    flange_length: 60
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    Z_x: 60554.7
    F_y: 172.4
    Mn: 10.44
    phi_Mn: 8.71

wind:
  wind_speed: 65.7
  b_height: 52.0
  b_length: 36.2
  b_width: 16.5
  exposure_cat: A
  occupancy_cat: III
  Imp_factor: 1.0
  K_d: 0.85
  K_h: 1.05
  K_ht: 1.0
  GC_pi: 0.18
  C_pl: 0.8
  q_zk: 2.1
  q_h: 2.5
  int_pressure: 0.5
  leeward_pressure: 1.64
  sidewall_pressure: 2.67

  b_rigidity: Rigid
  b_freq: 1.3
  damping: 0.02
  gust_factor: 0.85

  enclosure_type: Enclosed
  roof_type: Flat
  exposure_note: Urban area
  occupancy_note: Other structure
  location: Dhaka

  topography_type: Homogeneous
  topo_crest_side:
  topo_height:
  topo_length:
  topo_distance:

categories:
  - category_name: Typ. Floor-to-floor Facade
    # num_glass_units: 2
    glass_units:
      - glass_type: dgu
        length: 2700
        width: 900
        thickness1: 8.0
        gap: 12 
        thickness2: 8.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl1: 2.5
        nfl2: 2.5
        gtf1: 3.6
        gtf2: 3.6
        ls1: 2.0
        ls2: 2.0
        lr1: 3.6
        lr2: 3.6
        stress_ratio: 0.54
        load_x_area2: 
        def1: 16.2
        def2: 16.2
        allow_def: 20.6
        def_ratio: 0.84
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0
      
      - glass_type: sgu
        length: 2700
        width: 900
        thickness: 12.0
        grade: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl: 2.5
        gtf: 4.0
        lr: 6.4
        stress_ratio: 0.54
        load_x_area2: 
        def: 12.2
        allow_def: 16.5
        def_ratio: 0.74
        bite_req: 13.2
        bite_pro: 16.0
        glue_req: 4.2
        glue_pro: 6.0
      
      - glass_type: lgu
        length: 2700
        width: 900
        thickness1: 8.0
        thickness_inner: 1.52
        thickness2: 8.0
        chart_thickness: 16.0
        h_eff: 14.2
        grade: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl: 2.5
        gtf: 4.0
        lr: 6.4
        stress_ratio: 0.54
        load_x_area2: 
        def: 12.2
        allow_def: 16.5
        def_ratio: 0.74
        bite_req: 13.2
        bite_pro: 16.0
        glue_req: 4.2
        glue_pro: 6.0
      
      - glass_type: ldgu
        length: 2700
        width: 900
        thickness1_1: 8.0
        thickness_inner: 1.52
        thickness1_2: 8.0
        chart_thickness: 16.0
        gap: 12
        thickness2: 12.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl1: 2.5
        nfl2: 2.5
        gtf1: 3.6
        gtf2: 3.6
        ls1: 2.0
        ls2: 2.0
        lr1: 3.6
        lr2: 3.6
        stress_ratio: 0.54
        load_x_area2: 
        def1: 16.2
        def2: 16.2
        allow_def: 20.6
        def_ratio: 0.84
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0

      - glass_type: dgu
        length: 2700
        width: 900
        thickness1: 8.0
        gap: 12 
        thickness2: 8.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Point Fixed
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0

    frames:
      - frame_type: Floor-to-floor
        length: 3400
        width: 1200
        tran_spacing: 2700
        zone: Zone 4 (Mid Zone)
        system_type: Semi-unitized

        glass_thk: 16
        wind_pos: 2.4
        wind_neg: 3.2

        mullion: M 125x60x2.5 + RHS 85x50x4
        I_xa: 3558480.9
        I_xs: 1262531.3
        LS_a: 0.48
        LS_s: 0.52
        mul_mu: 10.45
        mul_vu: 11.57
        mul_def: 10.1
        mul_allow_def: 20
        mul_phi_Mn_a: 8.71
        mul_phi_Mn_s: 8.10
        mul_dc_ratio_a: 0.58
        mul_dc_ratio_s: 0.67

        transom: T 125x60x2.5
        tran_mu: 1.35
        tran_vu: 1.6
        tran_def_wind: 1.2 
        tran_def_dead: 1.6
        tran_allow_def: 6.8
        tran_phi_Mn: 4.26
        tran_dc_ratio: 0.23

    connections:
      - screw_nos: 4
        cleat_size: 25 x 32 x 3.5 (L = 85)
        screw_dia: 4.8
        head_dia: 10.5

        joint_fy: 1.2
        joint_fz: 2.6
        design_fy: 4.5
        design_fz: 1.2
        resultant_shear: 2.3

        t1: 3.5
        t2: 2.5
        tc: 2.5
        phi_Pnv: 3.35
        phi_Pnot: 1.06
        phi_Pnov: 5.71
        beta_pullover: 0.37
        beta_pullout: 0.58

    anchorage:
      - clump_type: Box Clump
        reaction_Ry: 12.3
        reaction_Rz: 3.2
        design_Ry: 22.0
        design_Rz: 7.5
        N_ua: 0
        N_ug: 0
        V_ua: 7.5
        V_ug: 30.0

        anchor_nos: 4
        anchor_dia: 12
        embed_depth: 70

        A_seN: 84.3
        f_uta: 500

        phi_Ncbg: 37.2

        phi_Vsa: 16.4
        A_VC: 70500
        A_VCO: 45000
        C_a1: 100
        C_a2: 500
        h_a: 300
        psi_ecV: 1.0
        psi_edV: 1.0
        psi_cV: 1.0
        psi_hV: 1.0
        l_e: 70
        V_b: 15.5
        phi_Vcbg: 17.0
        phi_Vcp: 67.2

        bp_length_N: 250
        bp_width_B: 120
        bp_thk: 6
        bp_d: 85
        bp_b: 50
        bp_m: 30
        bp_n: 20
        bp_lambda_n: 18
        bp_q: 12
        bp_bearing_Mu: 5.6
        bp_thk_bearing: 5.2
        bp_Tu:
        bp_x:
        bp_tension_Mu:
        bp_Beff:
        bp_thk_tension:
        bp_A1: 3422.5
        bp_fp_max:







  - category_name: Typ. Cont. Facade
    # num_glass_units: 1
    glass_units:
      - glass_type: sgu
        length: 2700
        width: 900
        thickness: 12.0
        grade: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl: 2.5
        gtf: 4.0
        lr: 6.4
        stress_ratio: 0.54
        load_x_area2: 
        def: 12.2
        allow_def: 16.5
        def_ratio: 0.74
        bite_req: 13.2
        bite_pro: 16.0
        glue_req: 4.2
        glue_pro: 6.0


