project_info:
  ref_no: RFA-001/CW/STR/2025
  project_name: Water Suppy and Distribution, Dhaka
  project_client: VolumeZero Ltd.
  rev_no: 02
  date: 20/11/2025

alum_profiles:
  - profile_name: M 125x60x2.5
    web_length: 125
    flange_length: 60
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    plastic_x: 35.9
    plastic_y: 58.4
    Z_x: 60554.7
    F_y: 172.4
    Mn_yield: 10.44
    Mn_lb: 9.68
    phi_Mn: 8.71
  
  - profile_name: M 145x67x2.5
    web_length: 145
    flange_length: 67
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    plastic_x: 35.9
    plastic_y: 58.4
    Z_x: 60554.7
    F_y: 172.4
    Mn_yield: 10.44
    Mn_lb: 9.68
    phi_Mn: 8.71

steel_profiles:
  - profile_name: RHS 110x45x2.5
    web_length: 125
    flange_length: 60
    web_thk: 2.5
    flange_thk: 4.49
    tor_constant: 2327814.4
    area: 1284.3
    I_xx: 3558480.9
    I_yy: 889366.9
    Y: 80
    X: 33.5
    S_x: 44481.0
    S_y: 26548.3
    Z_x: 60554.7
    F_y: 172.4
    Mn: 10.44
    phi_Mn: 8.71


wind:
  wind_speed: 65.7
  b_height: 52.0
  b_length: 36.2
  b_width: 16.5
  exposure_cat: A
  occupancy_cat: III
  Imp_factor: 1.0
  K_d: 0.85
  K_h: 1.05
  K_ht: 1.0
  GC_pi: 0.18
  C_pl: 0.8
  q_zk: 2.1
  q_h: 2.5
  int_pressure: 0.5
  leeward_pressure: 1.64
  sidewall_pressure: 2.67

  b_rigidity: Rigid
  b_freq: 1.3
  damping: 0.02
  gust_factor: 0.85

  enclosure_type: Enclosed
  roof_type: Flat
  exposure_note: Urban area
  occupancy_note: Other structure
  location: Dhaka

  topography_type: Homogeneous
  topography_type:
  topo_crest_side:
  topo_height:
  topo_length:
  topo_distance:

categories:
  - category_name: Typ. Cont. Facade
    num_glass_units: 2
    glass_units:
      - glass_type: dgu
        length: 2700
        width: 900
        thickness1: 8.0
        gap: 12 
        thickness2: 8.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl1: 2.5
        nfl2: 2.5
        gtf1: 3.6
        gtf2: 3.6
        ls1: 2.0
        ls2: 2.0
        lr1: 3.6
        lr2: 3.6
        stress_ratio: 0.54
        load_x_length4: 
        def1: 16.2
        def2: 16.2
        allow_def: 20.6
        def_ratio: 0.84
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0
      
      - glass_type: sgu
        length: 2700
        width: 900
        thickness: 12.0
        grade: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl: 2.5
        gtf: 4.0
        lr: 6.4
        stress_ratio: 0.54
        load_x_length4: 
        def: 12.2
        allow_def: 16.5
        def_ratio: 0.74
        bite_req: 13.2
        bite_pro: 16.0
        glue_req: 4.2
        glue_pro: 6.0
      
      - glass_type: lgu
        length: 2700
        width: 900
        thickness1: 8.0
        thickness_inner: 1.52
        thickness2: 8.0
        chart_thickness: 16.0
        h_eff: 14.2
        grade: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl: 2.5
        gtf: 4.0
        lr: 6.4
        stress_ratio: 0.54
        load_x_length4: 
        def: 12.2
        allow_def: 16.5
        def_ratio: 0.74
        bite_req: 13.2
        bite_pro: 16.0
        glue_req: 4.2
        glue_pro: 6.0
      
      - glass_type: ldgu
        length: 2700
        width: 900
        thickness1_1: 8.0
        thickness_inner: 1.52
        thickness1_2: 8.0
        chart_thickness: 16.0
        gap: 12
        thickness2: 12.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl1: 2.5
        nfl2: 2.5
        gtf1: 3.6
        gtf2: 3.6
        ls1: 2.0
        ls2: 2.0
        lr1: 3.6
        lr2: 3.6
        stress_ratio: 0.54
        load_x_length4: 
        def1: 16.2
        def2: 16.2
        allow_def: 20.6
        def_ratio: 0.84
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0

    frame_type: single
    conn_type: type-01
    anchorage_type: box
  
  - category_name: Typ. Cont. Facade
    num_glass_units: 1
    glass_units:
      - glass_type: dgu
        length: 2700
        width: 900
        thickness1: 8.0
        gap: 12 
        thickness2: 8.0
        grade1: FT
        grade2: FT
        wind_load: 2.5
        support_type: Four Edges
        nfl1: 2.5
        nfl2: 2.5
        gtf1: 3.6
        gtf2: 3.6
        ls1: 2.0
        ls2: 2.0
        lr1: 3.6
        lr2: 3.6
        stress_ratio: 0.54
        r_0: 2.3
        r_1: 1.2
        r_2: 3.6
        min_thk1: 7.46
        min_thk2: 7.46
        x1: 2.4
        x2: 2.4
        def1: 16.2
        def2: 16.2
        allow_def: 20.6
        def_ratio: 0.84
        bite_req: 12.4
        bite_pro: 1.6
        glue_req: 3.2
        glue_pro: 6.0
    
    frame_type: single
    conn_type: type-01
    anchorage_type: box


